### ISSUE TITLE
请问下加速前后的速度对比表

### ISSUE THREAD

**Issue by lazyfan** [DataXujing/Co-DETR-TensorRT#1]
感谢大佬的工作！请问下有没有加速前后的速度对比表

**Comment by DataXujing** [comment]
![捕获](https://github.com/user-attachments/assets/366f06af-da51-49ba-8e82-c95a212b2c5a)


这是在NVIDIA GTX 1660 (6G)显卡上的推理延时分析，你可以参考这个时间测试mmdetection下的推理延时。我线下并没有做mmdetection和TRT在延时和吞吐上的分析，仅仅是在识别精度上比如平均相对误差的分析上TRT是没有问题的。
