### ISSUE TITLE
添加nms的问题

### ISSUE THREAD

**Issue by chinabing** [DataXujing/Co-DETR-TensorRT#2]
你好，我在最后一步添加nms时报错了，我把模型打印了下
![image](https://github.com/user-attachments/assets/ab833156-0ff0-4304-8b24-caf2eebb6bf8)

跟你代码里的不匹配，
score_node_name = "Sigmoid_8437"
index_node_name = "Div_8449"
box_node_name = "ScatterND_8577"

不知道如何修改，请帮忙看下，谢谢

**Comment by DataXujing** [comment]
用Netron 查看一下自己转出来的onnx的结点名称，修改一下，不同环境转出的onnx结点的name可能不一样，注意修改上述三个结点的name

**Comment by moneyisallyouneed** [comment]
> 用Netron 查看一下自己转出来的onnx的结点名称，修改一下，不同环境转出的onnx结点的name可能不一样，注意修改上述三个结点的name

我也不太会改。请问可以简单说一下怎么看吗？
