### ISSUE TITLE
KeyError: 'CoDETR is not in the mmengine

### ISSUE THREAD

**Issue by moneyisallyouneed** [DataXujing/Co-DETR-TensorRT#4]
您好~ 我新创建了一个conda环境，安装好了tensorrt，并且按照您的步骤安装了mmdet和mmcv，但是在转换模型的时候报这个错，请问怎么解决呢

KeyError: 'CoDETR is not in the mmengine::model registry. Please check whether the value of `CoDETR` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

以下是我的环境：
11/30 16:12:45 - mmengine - INFO - **********Environmental information**********
11/30 16:12:45 - mmengine - INFO - sys.platform: linux
11/30 16:12:45 - mmengine - INFO - Python: 3.9.20 (main, Oct  3 2024, 07:27:41) [GCC 11.2.0]
11/30 16:12:45 - mmengine - INFO - CUDA available: True
11/30 16:12:45 - mmengine - INFO - MUSA available: False
11/30 16:12:45 - mmengine - INFO - numpy_random_seed: 2147483648
11/30 16:12:45 - mmengine - INFO - GPU 0,1,2,3,4,5: NVIDIA GeForce RTX 4090
11/30 16:12:45 - mmengine - INFO - CUDA_HOME: /usr/local/cuda-11.8
11/30 16:12:45 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.8, V11.8.89
11/30 16:12:45 - mmengine - INFO - GCC: gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
11/30 16:12:45 - mmengine - INFO - PyTorch: 2.0.1+cu118
11/30 16:12:45 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.8
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.7
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

11/30 16:12:45 - mmengine - INFO - TorchVision: 0.15.2+cu118
11/30 16:12:45 - mmengine - INFO - OpenCV: 4.10.0
11/30 16:12:45 - mmengine - INFO - MMEngine: 0.10.5
11/30 16:12:45 - mmengine - INFO - MMCV: 2.0.0
11/30 16:12:45 - mmengine - INFO - MMCV Compiler: GCC 9.3
11/30 16:12:45 - mmengine - INFO - MMCV CUDA Compiler: 11.8
11/30 16:12:45 - mmengine - INFO - MMDeploy: 1.3.1+bc75c9d
11/30 16:12:45 - mmengine - INFO - 

11/30 16:12:45 - mmengine - INFO - **********Backend information**********
11/30 16:12:45 - mmengine - INFO - tensorrt:    8.5.3.1
11/30 16:12:45 - mmengine - INFO - tensorrt custom ops: NotAvailable
11/30 16:12:45 - mmengine - INFO - ONNXRuntime: 1.8.1
11/30 16:12:45 - mmengine - INFO - ONNXRuntime-gpu:     1.19.2
11/30 16:12:45 - mmengine - INFO - ONNXRuntime custom ops:      Available
11/30 16:12:45 - mmengine - INFO - pplnn:       None
11/30 16:12:45 - mmengine - INFO - ncnn:        None
11/30 16:12:45 - mmengine - INFO - snpe:        None
11/30 16:12:45 - mmengine - INFO - openvino:    None
11/30 16:12:45 - mmengine - INFO - torchscript: 2.0.1+cu118
11/30 16:12:45 - mmengine - INFO - torchscript custom ops:      NotAvailable
11/30 16:12:45 - mmengine - INFO - rknn-toolkit:        None
11/30 16:12:45 - mmengine - INFO - rknn-toolkit2:       None
11/30 16:12:45 - mmengine - INFO - ascend:      None
11/30 16:12:45 - mmengine - INFO - coreml:      None
11/30 16:12:45 - mmengine - INFO - tvm: None
11/30 16:12:45 - mmengine - INFO - vacc:        None
11/30 16:12:45 - mmengine - INFO - 

11/30 16:12:45 - mmengine - INFO - **********Codebase information**********
11/30 16:12:45 - mmengine - INFO - mmdet:       3.3.0
11/30 16:12:45 - mmengine - INFO - mmseg:       None
11/30 16:12:45 - mmengine - INFO - mmpretrain:  None
11/30 16:12:45 - mmengine - INFO - mmocr:       None
11/30 16:12:45 - mmengine - INFO - mmagic:      None
11/30 16:12:45 - mmengine - INFO - mmdet3d:     None
11/30 16:12:45 - mmengine - INFO - mmpose:      None
11/30 16:12:45 - mmengine - INFO - mmrotate:    None
11/30 16:12:45 - mmengine - INFO - mmaction:    None
11/30 16:12:45 - mmengine - INFO - mmrazor:     None
11/30 16:12:45 - mmengine - INFO - mmyolo:      None

非常感谢~

**Comment by DataXujing** [comment]
可能是环境安装问题，检查一下环境特别是库的版本，还有就是转onnx传的配置文件是否正确
